// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc1332.Hilgenfeld.subsystems;

import org.usfirst.frc1332.Hilgenfeld.RobotMap;
import org.usfirst.frc1332.Hilgenfeld.commands.*;

import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.buttons.JoystickButton;
import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class GripBase extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    Compressor compressor1 = RobotMap.gripBaseCompressor1;
    Solenoid soleLF = RobotMap.gripBaseSoleLF;
    Solenoid soleRT = RobotMap.gripBaseSoleRT;
    Solenoid soleLF2 = RobotMap.gripBaseSoleLF2;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
    public void AirOn(){
    	compressor1.start();
    }
    public void AirOff(){
    	compressor1.getPressureSwitchValue();
    }
    
    public void LtOn(){
        soleLF.set(true);
        soleRT.set(false);
        soleLF2.set(true);
    }
    
    public void RtOn(){
        soleLF.set(false);
        soleRT.set(true);
        soleLF2.set(false);
    }
    
    public void SoleOff(){
    	soleLF.set(false);
    	soleRT.set(false);
    	soleLF2.set(false);
    }
}

