// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc1332.TestBot2016;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.AnalogGyro;
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Talon;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController driveBaseLF;
    public static SpeedController driveBaseLR;
    public static SpeedController driveBaseRF;
    public static SpeedController driveBaseRR;
    public static RobotDrive driveBaseRobotDrive41;
    public static AnalogGyro driveBaseAnalogGyro0;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveBaseLF = new Talon(0);
        LiveWindow.addActuator("DriveBase", "LF", (Talon) driveBaseLF);
        
        driveBaseLR = new Talon(1);
        LiveWindow.addActuator("DriveBase", "LR", (Talon) driveBaseLR);
        
        driveBaseRF = new Talon(2);
        LiveWindow.addActuator("DriveBase", "RF", (Talon) driveBaseRF);
        
        driveBaseRR = new Talon(3);
        LiveWindow.addActuator("DriveBase", "RR", (Talon) driveBaseRR);
        
        driveBaseRobotDrive41 = new RobotDrive(driveBaseLF, driveBaseLR,
              driveBaseRF, driveBaseRR);
        
        driveBaseRobotDrive41.setSafetyEnabled(true);
        driveBaseRobotDrive41.setExpiration(0.1);
        driveBaseRobotDrive41.setSensitivity(0.5);
        driveBaseRobotDrive41.setMaxOutput(0.8);

        driveBaseRobotDrive41.setInvertedMotor(RobotDrive.MotorType.kFrontRight, true);
        driveBaseRobotDrive41.setInvertedMotor(RobotDrive.MotorType.kRearRight, true);
        driveBaseAnalogGyro0 = new AnalogGyro(0);
        LiveWindow.addSensor("DriveBase", "AnalogGyro 0", driveBaseAnalogGyro0);
        driveBaseAnalogGyro0.setSensitivity(0.007);

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
